# https://www.faqforge.com/windows/configure-dhcp-powershell/

- name: Install DHCP
  ansible.windows.win_feature:
    name: DHCP
    state: present
    include_management_tools: true
  register: win_feature

- name: Reboot if installing windows feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

# - name: Reboot if installing windows feature requires it
#   ansible.windows.win_reboot:

- name: Display dhcp variables in use
  ansible.builtin.debug:
    msg:
      - "windows_domain_dhcp_domain_name: {{ windows_domain_dhcp_domain_name }}"
      - "windows_domain_dhcp_dc_name: {{ windows_domain_dhcp_dc_name }}"
      - "windows_domain_dhcp_dns_ip: {{ windows_domain_dhcp_dns_ip }}"
      - "windows_domain_dhcp_ip_from: {{ windows_domain_dhcp_ip_from }}"
      - "windows_domain_dhcp_ip_to: {{ windows_domain_dhcp_ip_to }}"
      - "windows_domain_dhcp_ip_mask: {{ windows_domain_dhcp_ip_mask }}"
      - "windows_domain_dhcp_lease_duration: {{ windows_domain_dhcp_lease_duration }}"


- name: Allow dhcp in dc
  ansible.windows.win_shell: |
    Add-DHCPServerInDC -DNSName {{ windows_domain_dhcp_dc_name }}.{{ windows_domain_dhcp_domain_name }}
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ windows_domain_dhcp_domain_name }}\\Administrator"
    ansible_become_password: "{{ windows_domain_dhcp_domain_password }}"

- name: Set dhcp scope
  ansible.windows.win_shell: |
    $s = Get-DhcpServerv4Scope
    if ($null -eq $s) {
      Add-DhcpServerV4Scope -Name "DHCP Scope" -StartRange {{ windows_domain_dhcp_ip_from }} -EndRange {{ windows_domain_dhcp_ip_to }} -SubnetMask {{ windows_domain_dhcp_ip_mask }} -LeaseDuration {{ windows_domain_dhcp_lease_duration }}
    }

- name: Get default gateway
  ansible.windows.win_shell: |
    (Get-NetRoute -DestinationPrefix "0.0.0.0/0").NextHop
  register: ip_gateway_command

- name: Set ip_gateway
  ansible.builtin.set_fact:
    ip_gateway: "{{ ip_gateway_command.stdout | trim }}"

- name: Add DNS Server, Router Gateway Options in DHCP
  ansible.windows.win_shell: |
    Set-DhcpServerV4OptionValue -DnsServer {{ windows_domain_dhcp_dns_ip }} -Router {{ ip_gateway }}

# - name: create server option boot server hostname (MECM)
#   win_shell: |
#     Set-DhcpServerV4OptionValue -OptionId 66 -Value {{sccm_server}}
#
# - name: create boot file name (SMSBoot\x64\wdsnbp.com)
#   win_shell: |
#     Set-DhcpServerV4OptionValue -OptionId 67 -Value "SMSBoot\x64\wdsnbp.com"

# https://www.systemsitpro.com/2017/12/how-to-configure-dhcp-for-pxe-booting.html
# https://www.it-connect.fr/serveurs-dhcp-wds-boot-pxe-bios-et-uefi/
# Add-DhcpServerv4OptionDefinition -ComputerName SRV-ADDS-01 -Name PXEClient -Description "PXE Support" -OptionId 060 -Type String
- name: Restart service DHCP
  ansible.windows.win_service:
    name: 'dhcpserver'
    state: restarted
