- name: Render full JSON payload
  ansible.builtin.set_fact:
    wallix_bastion_user_json: "{{ lookup('template', 'user.json.j2') }}"

#- name: print json
#  ansible.builtin.debug:
#    var: wallix_bastion_user_json

- name: "Creating user {{ wallix_bastion_user_name }}"
  ansible.builtin.uri:
    url: "{{ wallix_bastion_user_url }}/users"
    method: POST
    body_format: json
    validate_certs: false
    status_code:
      - 204
    headers:
      Cookie: "wab_session_id={{ wallix_bastion_user_cookie.cookies['wab_session_id'] }}"
    body: "{{ wallix_bastion_user_json }}"



