- name: Enable UAC
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    data: "{{ 0 if uac_level == 0 else 1 }}"
    type: dword
  when: uac_level is defined


- name: Set ConsentPromptBehaviorAdmin
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: ConsentPromptBehaviorAdmin
    data: "{{ uac_level }}"
    type: dword
  when: uac_level is defined
