- name: Create Connectors
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $ModulePath
      )
      $Ansible.Failed = $false
      $Ansible.Changed = $false
      $Ansible.Result = $null | ConvertTo-Json

      Import-Module $ModulePath
      Connect-ExchangeServer -auto -ClientApplication:ManagementShell
      $Ansible.Result = Get-EmailAddressPolicy | Select-Object Name,Priority,Enabled*,RecipientFilterType,RecipientContainer,RecipientFilter,IncludedRecipients,Conditional* |  ConvertTo-Json
      # New-SendConnector -Name "Internal Send Connector" -Internal -AddressSpaces "SMTP:haas.local;1" -IsScopedConnector $false -DNSRoutingEnabled $true -SourceTransportServers "YourExchangeServerName"
    parameters:
      ModulePath: "{{ wd_xchg_cfg_pwsh_module }}"
  register: exchange_cfg_result
#  error_action: silently_continue  # ignore any errors and exceptions raised.
#  error_action: continue (default) # errors are present in the error return value but only terminating exceptions will stop the script from continuing and set it as failed.
#  error_action: stop               # treat errors like exceptions, will stop the script and set it as failed
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"

#- name: Debug command
#  ansible.builtin.debug: 
#    var:  exchange_cfg_result

    