- name: Create boundary
  sccm_boundary:
    name: "ADSiteBoundary01"
    type: "ADSite"
    value: "Default-First-Site-Name"
    site_code: "{{ sccm_site_code }}"
    server: "{{ hostname }}.{{ domain_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
    ansible_become_flags: logon_flags=

- name: Create boundary group
  sccm_boundary_group:
    name: "BoundaryGroup01"
    server: "{{ hostname }}.{{ domain_name }}"
    site_code: "{{ sccm_site_code }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
    ansible_become_flags: logon_flags=

- name: Add boundary to boundary group
  sccm_boundary_to_boundarygroup:
    boundary_name: "ADSiteBoundary01"
    boundary_group: "BoundaryGroup01"
    site_code: "{{ sccm_site_code }}"
    server: "{{ hostname }}.{{ domain_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
    ansible_become_flags: logon_flags=
