- name: Ensure chocolatey is installed
  chocolatey.chocolatey.win_chocolatey:
    name:
      - chocolatey
      - chocolatey-core.extension
    state: present

- name: Disable enhanced exit codes
  chocolatey.chocolatey.win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: Install multiple packages sequentially
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - notepadplusplus
    - putty
    - python
    - git
    - 7zip
    - sysinternals
    - wget
    - pstools
  ignore_errors: true