- name: Install capabilities
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $C
      )
      Add-WindowsCapability -Online -Name $C
    error_action: stop
    parameters:
      C: "{{ item }}"
#  vars:
#    ansible_become: true
#    ansible_become_method: runas
#    ansible_become_user: "{{ wd_mbr_capab_domain_name }}\\Administrator"
#    ansible_become_password: "{{wd_mbr_capab_domain_password }}"
  with_items: "{{ wd_mbr_capab_capabilities }}"
  register: install_capabilities
