- name: Install MECM console
  ansible.windows.win_shell: .\consolesetup.exe  /q "TargetDir=C:\Program Files\ConfigMgr Console" DefaultSiteServerName="{{ cfgmgr_server_cn }}.{{ cfgmgr_domain_name }}"
  args:
    chdir: C:\setup\cd.retail.LN\SMSSETUP\BIN\I386\
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ cfgmgr_domain_name }}\\Administrator"
    ansible_become_password: "{{ cfgmgr_domain_password }}"