- name: Create Wallix Bastion domain
  block:
    - name: Render Wallix Bastion JSON payload
      ansible.builtin.set_fact:
        wallix_bastion_domain_json: "{{ lookup('template', 'domain.json.j2') }}"

    - name: Debug Wallix Bastion JSON payload
      ansible.builtin.debug:
        var: wallix_bastion_domain_json

    - name: "Create Wallix Bastion domain {{ wallix_bastion_domain_name }}"
      ansible.builtin.uri:
        url: "{{ wallix_bastion_domain_url }}/domains"
        method: POST
        body_format: json
        validate_certs: false
        status_code:
          - 204
        headers:
          X-Auth-User: "{{ wallix_bastion_domain_api_key.user }}"
          X-Auth-Key: "{{  wallix_bastion_domain_api_key.key }}"
        body: "{{ wallix_bastion_domain_json }}"
  when: wallix_bastion_domain_action == "create"

- name: Get Wallix Bastion domain
  block:
    - name: "Get Wallix Bastion domain id for {{ wallix_bastion_domain_name }}"
      ansible.builtin.uri:
        url: "{{ wallix_bastion_domain_url }}/domains/?q=domain_name={{ wallix_bastion_domain_name }}"
        method: GET
        body_format: json
        validate_certs: false
        status_code:
          - 200
        headers:
          X-Auth-User: "{{ wallix_bastion_domain_api_key.user }}"
          X-Auth-Key: "{{  wallix_bastion_domain_api_key.key }}"
      register: wallix_response

    #- name: Display wallix_response
    #  ansible.builtin.debug:
    #    var: wallix_response

    - name: Extract ID from response and update device entry
      ansible.builtin.set_fact:
        wallix_bastion_domain_data_updated: {
          'wallix_domain_id': "{{ (wallix_response.json[0].id | default('UNKNOWN')) }}",
          'domain_name': "{{ wallix_bastion_domain_name }}",
          'domain_real_name': "{{ wallix_bastion_domain_data.domain_real_name }}",
          'description': "{{ wallix_bastion_domain_data.description }}",
          'admin_account': "{{ wallix_bastion_domain_data.admin_account }}",
          'enable_password_change': "{{ wallix_bastion_domain_data.enable_password_change }}",
          'password_change_policy': "{{ wallix_bastion_domain_data.password_change_policy }}",
          'password_change_plugin': "{{ wallix_bastion_domain_data.password_change_plugin }}",
          'password_change_plugin_parameters': "{{ wallix_bastion_domain_data.password_change_plugin_parameters }}",
          'ca_private_key': "{{ wallix_bastion_domain_data.ca_private_key }}",
          'passphrase': "{{ wallix_bastion_domain_data.passphrase }}"
        }

    - name: Extract ID from response and update device entry
      ansible.builtin.set_fact:
        wallix_bastion_domain_data: "{{ wallix_bastion_domain_data_updated }}"

    # - name: Display wallix_bastion_domain_data
    #   ansible.builtin.debug:
    #     var: wallix_bastion_domain_data
  when: wallix_bastion_domain_action == "get"

- name: Set Wallix Bastion domain econciliation account
  block:
    - name: Render Wallix Bastion JSON payload
      ansible.builtin.set_fact:
        wallix_bastion_domain_json: "{{ lookup('template', 'set_reconciliation.json.j2') }}"

    - name: Debug Wallix Bastion JSON payload
      ansible.builtin.debug:
        var: wallix_bastion_domain_json

    - name: "Update Wallix Bastion domain {{ wallix_bastion_domain_name }}"
      ansible.builtin.uri:
        url: "{{ wallix_bastion_domain_url }}/domains/{{ wallix_bastion_domain_data.wallix_domain_id }}"
        method: PUT
        body_format: json
        validate_certs: false
        status_code:
          - 204
        headers:
          X-Auth-User: "{{ wallix_bastion_domain_api_key.user }}"
          X-Auth-Key: "{{  wallix_bastion_domain_api_key.key }}"
        body: "{{ wallix_bastion_domain_json }}"
  when: wallix_bastion_domain_action == "set_reconciliation"
