- name: Add dns server zone
  community.windows.win_dns_zone:
    name: "{{ wd_dns_forwarder_zone_name }}"
    type: forwarder
    replication: "{{ wd_dns_forwarder_replication }}"
    dns_servers:
      - "{{ wd_dns_forwarder_master_server }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ wd_dns_forwarder_domain_name }}\\Administrator"
    ansible_become_password: "{{ wd_dns_forwarder_domain_password }}"
