---
# https://clintboessen.blogspot.com/2010/04/group-scopes.html
# https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc755692(v=ws.10)

- name: Create domain groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: "{{ item.value.scope | default('domainlocal') }}"
    path: "{{ item.value.path }}"
    managed_by: "{{ item.value.managed_by | default('') }}"
    state: present
    domain_username: "{{ domain_name }}\\Administrator"
    domain_password: "{{ domain_password }}"
  with_dict: "{{ ad_groups }}"
  when: domain_data_action == "create"

- name: Synchronizes all domains before adding members to groups
  ansible.windows.win_shell: repadmin /syncall /Ade
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ domain_name }}\\Administrator"
  vars:
    ansible_become_pass: "{{ domain_password }}"
  when: domain_data_action == "add_members"

- name: "Add members to domain groups"
  microsoft.ad.group:
    domain_username: "{{ domain_name }}\\Administrator"
    domain_password: "{{ domain_password }}"
    name: "{{ item.key }}"
    path: "{{ item.value.path }}"
    members:
      add: "{{ item.value.members }}"
  with_dict: "{{ ad_groups }}"
  when: domain_data_action == "add_members"
  register: group_membership
  until: "group_membership is not failed"
  retries: 3
  delay: 60

- name: "Add foreign users to domain group"
  ansible.builtin.include_tasks: add_foreign.yml
  vars:
    local_group_name: "{{ group.key }}"
    object_type: "user"
    foreign_objects: "{{ group.value.foreign_users | default({}) }}"
  with_dict: "{{ ad_groups }}"
  loop_control:
    loop_var: group
  when: domain_data_action == "add_members" and domain_data_add_foreign

- name: "Add foreign GMSA to domain group"
  ansible.builtin.include_tasks: add_foreign.yml
  vars:
    local_group_name: "{{ group.key }}"
    object_type: "gmsa"
    foreign_objects: "{{ group.value.foreign_gmsas | default({}) }}"
  with_dict: "{{ ad_groups }}"
  loop_control:
    loop_var: group
  when: domain_data_action == "add_members" and domain_data_add_foreign

- name: "Add foreign Computer to domain group"
  ansible.builtin.include_tasks: add_foreign.yml
  vars:
    local_group_name: "{{ group.key }}"
    object_type: "computer"
    foreign_objects: "{{ group.value.foreign_computers | default({}) }}"
  with_dict: "{{ ad_groups }}"
  loop_control:
    loop_var: group
  when: domain_data_action == "add_members" and domain_data_add_foreign

- name: "Add foreign groups to domain group"
  ansible.builtin.include_tasks: add_foreign.yml
  vars:
    local_group_name: "{{ group.key }}"
    object_type: "group"
    foreign_objects: "{{ group.value.foreign_groups | default({}) }}"
  with_dict: "{{ ad_groups }}"
  loop_control:
    loop_var: group
  when: domain_data_action == "add_members" and domain_data_add_foreign
