---
- name: Install WindowsFeature RSAT-ADDS
  ansible.windows.win_feature:
    name: RSAT-DNS-Server
    state: present
    include_management_tools: true

- name: Add Mail A record
  ansible.windows.win_dns_record:
    type: A
    name: "mail"
    value: "{{ xchg_domain_ip }}"
    ttl: 3600
    zone: "{{ xchg_domain_name }}"
    state: present
    computer_name: "{{ xchg_domain_dc_name}}.{{ xchg_domain_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ xchg_domain_name }}\\Administrator"
    ansible_become_password: "{{ xchg_domain_password }}"

- name: Add OWA CNAME record
  ansible.windows.win_dns_record:
    type: "CNAME"
    name: "owa"
    value: "mail.{{ xchg_domain_name }}"
    ttl: 3600
    zone: "{{ xchg_domain_name }}"
    state: present
    computer_name: "{{ xchg_domain_dc_name }}.{{ xchg_domain_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ xchg_domain_name }}\\Administrator"
    ansible_become_password: "{{ xchg_domain_password }}"

- name: Add autodiscover CNAME record
  ansible.windows.win_dns_record:
    type: "CNAME"
    name: "autodiscover"
    value: "mail.{{ xchg_domain_name }}"
    ttl: 3600
    zone: "{{ xchg_domain_name }}"
    state: present
    computer_name: "{{ xchg_domain_dc_name }}.{{ xchg_domain_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ xchg_domain_name }}\\Administrator"
    ansible_become_password: "{{ xchg_domain_password }}"

- name: Add autodiscover service record
  ansible.windows.win_dns_record:
    type: "SRV"
    name: "_autodiscover"
    port: 443
    value: "{{ xchg_hostname }}.{{ xchg_domain_name }}"
    priority: 0
    weight: 0
    ttl: 3600
    zone: "{{ xchg_domain_name }}"
    state: present
    computer_name: "{{ xchg_domain_dc_name }}.{{ xchg_domain_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ xchg_domain_name }}\\Administrator"
    ansible_become_password: "{{ xchg_domain_password }}"
