- name: Add Replication Subnet
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $IPAddress,
          [String]
          $Prefix
      )
      Import-Module ActiveDirectory
      #$SubnetName = "172.16.2.1/24"
      $SubnetMask = [ipaddress]([math]::pow(2, 32) -1 -bxor [math]::pow(2, (32 - $Prefix))-1)
      $IP = [ipaddress]$IPAddress
      $Subnet = [ipaddress]$SubnetMask.IPAddressToString
      $NetID = [ipaddress]($IP.Address -band $Subnet.Address)
      $SubnetName = "$($NetID.IPAddressToString)/$($Prefix)"
      try {
        $Subnet = Get-ADReplicationSubnet -Identity $SubnetName
      }
      catch {
        $Subnet = $null
      }
      if ($null -ne $Subnet) {
        $Ansible.Changed = $false
      }
      else {
        $Ansible.Changed = $true
        New-ADReplicationSubnet -Name $SubnetName -Site "Default-First-Site-Name"
      }
    parameters:
      IPAddress: "{{ ip_address }}"
      Prefix: "{{ network_prefix: }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
    ansible_become_flags: logon_flags=