---
- name: Restart reflector
  ansible.builtin.service:
    name: reflector
    state: restarted
    enabled: true
- name: Restart reflector timer
  ansible.builtin.systemd:
    name: reflector.timer
    state: restarted
    enabled: true
