---
- name: Assert proper distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Archlinux']
    quiet: true

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Include common variables
  ansible.builtin.include_vars: "common.yml"

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: Restart updatedb
  ansible.builtin.service:
    name: plocate-updatedb
    state: restarted
    enabled: true
  when: ansible_distribution == "Archlinux" and __pacman.changed

- name: Restart updatedb timer
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    state: restarted
    enabled: true
  when: ansible_distribution == "Archlinux" and __pacman.changed
