- name: Render Wallix Bastion JSON payload
  ansible.builtin.set_fact:
    wallix_bastion_domain_json: "{{ lookup('template', 'set_reconciliation.json.j2') }}"

- name: Debug Wallix Bastion JSON payload
  ansible.builtin.debug:
    var: wallix_bastion_domain_json

- name: "Update Wallix Bastion domain {{ domain.key }}"
  ansible.builtin.uri:
    url: "{{ wallix_bastion_domains_url }}/domains/{{domain.value.wallix_domain_id }}"
    method: PUT
    body_format: json
    validate_certs: false
    status_code:
      - 204
    headers:
      X-Auth-User: "{{ wallix_bastion_domains_api_key.user }}"
      X-Auth-Key: "{{  wallix_bastion_domains_api_key.key }}"
    body: "{{ wallix_bastion_domain_json }}"