---
- name: Restart updatedb
  ansible.builtin.service:
    name: updatedb
    state: restarted
    enabled: true

- name: Restart updatedb timer
  ansible.builtin.systemd:
    name: updatedb.timer
    state: restarted
    enabled: true
