- name: "Prioritize the local interface as the default for routing {{ wd_join_srv_domain_adapter }}"
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "{{ wd_join_srv_domain_adapter }}" -InterfaceMetric 10
  when: wd_join_srv_two_adapters

- name: "Set configure dns to domain_dc_ip"
  ansible.windows.win_dns_client:
    adapter_names: "{{ wd_join_srv_domain_adapter }}"
    ipv4_addresses:
      - "{{ wd_join_srv_domain_dc_ip }}"
    log_path: C:\dns_log.txt

- name: Verify File Server Role is installed.
  ansible.windows.win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: true

- name: "Add server to domain"
  microsoft.ad.membership:
    hostname: "{{ wd_join_srv_hostname }}"
    dns_domain_name: "{{ wd_join_srv_domain_name }}"
    domain_admin_user: "Administrator@{{ wd_join_srv_domain_name }}"
    domain_admin_password: "{{ wd_join_srv_domain_password }}"
    domain_ou_path: "{{ wd_join_srv_path }}"
    state: domain
    reboot: true
  register: domain_state
