---
- name: Assert proper distribution
  assert:
    that:
      - ansible_distribution in ['Archlinux']
    quiet: true


- name: Check blackarch repo absent
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^[blackarch]'
    line: '[blackarch]'
    state: present
  check_mode: true
  register: __blackarch_repo
  changed_when: false

- name: Install BlackArch
  block:
    - name: Get strap
      ansible.builtin.get_url:
        url: "{{ _blackarch_strap_url }}"
        checksum: "{{ _blackarch_strap_checksum }}"
        dest: /tmp/strap.sh
        mode: '0700'
        owner: root
        group: root

    - name: Check blackarch repo absent
      ansible.builtin.lineinfile:
        path: /tmp/strap.sh
        regexp: 'verify_keyring$'
        state: absent
  
    - name: Run strap
      ansible.builtin.command: /tmp/strap.sh
      register: __strap
      notify: Upgrade packages
  when: __blackarch_repo.msg == 'line added'
