- name: Enable run as PPL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RunAsPPL
    data: "{{ 1 if run_as_ppl == true else 0 }}"
    type: dword
  when: w_cfg_run_as_ppl is defined
