---
- name: Enable sa account
  ansible.windows.win_shell: |
    SqlCmd {{ connection_type }} -Q "ALTER LOGIN sa ENABLE"
    SqlCmd {{ connection_type }} -Q "ALTER LOGIN sa WITH PASSWORD = '{{ sa_password }}' , CHECK_POLICY=OFF"
  become: true
  become_method: runas
  become_user: "{{ SQLSVCACCOUNT }}"
  vars:
    ansible_become_pass: "{{ SQLSVCPASSWORD }}"

- name: enable MSSQL authentication and windows authent
  ansible.windows.win_shell: |
    SqlCmd {{ connection_type }} -Q "EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2"
  become: true
  become_method: runas
  become_user: "{{ SQLSVCACCOUNT }}"
  vars:
    ansible_become_pass: "{{ SQLSVCPASSWORD }}"
