- name: Create a directory for installer download
  ansible.windows.win_file:
    path: c:\setup
    state: directory

- name: Create a directory for installer extraction
  ansible.windows.win_file:
    path: c:\setup\mssql
    state: directory

- name: Check SQL Server Manager Studio installer exists
  ansible.windows.win_stat:
    path: c:\setup\mssql\SSMS_installer.exe
  register: ssms_installer_file

- name: Get the installer
  ansible.windows.win_get_url:
    url: 'https://aka.ms/ssmsfullsetup'
    dest: 'c:\setup\mssql\SSMS_installer.exe'
  when: not ssms_installer_file.stat.exists

- name: Check SSMS installation already done
  ansible.windows.win_stat:
    path: "C:\\Program Files (x86)\\Microsoft SQL Server Management Studio 18"
  register: ssms_installation

- name: Install SSMS
  ansible.windows.win_command: c:\setup\mssql\SSMS_installer.exe /install /quiet /norestart
  register: install_ssmss
  when: not ssms_installation.stat.exists

- name: Reboot after install
  ansible.windows.win_reboot:
    reboot_timeout: 600
  when: not ssms_installation.stat.exists
