---

- name: Windows | Check for xNetworking Powershell module
  community.windows.win_psmodule:
    name: xNetworking
    state: present

- name: Manage firewall rules
  ansible.builtin.include_tasks: fw_rules.yml

- name: Manage firewall rules
  ansible.builtin.include_tasks: fw_profiles.yml

# Change network profile of domainAuthenticated interface
# https://woshub.com/how-to-change-a-network-type-from-public-to-private-in-windows/

- name: Manage firewall rules
  ansible.builtin.include_tasks: net_profiles.yml
