- name: Refresh
  ansible.windows.win_command: gpupdate /force

- name: Install windows features - RSAT-ADDS
  ansible.windows.win_feature:
    name: RSAT-ADDS
    state: present
    include_management_tools: true
    include_sub_features: true
  register: features_rsat

- name: Install ADCSTemplate module
  community.windows.win_psmodule:
    name: ADCSTemplate
    skip_publisher_check: true
    state: present

- name: create a directory for templates
  ansible.windows.win_file: 
    path: c:\setup
    state: directory

- name: Copy templates json
  ansible.windows.win_copy:
    src: "files/{{ item }}.json"
    dest: "C:\\setup\\{{ item }}.json"
  with_items: "{{ cert_templates }}"

- name: Install templates
  ansible.windows.win_shell: |
    if (-not(Get-ADCSTemplate -DisplayName "{{ item }}")) { New-ADCSTemplate -DisplayName "{{ item }}" -JSON (Get-Content c:\setup\{{ item }}.json -Raw) -Identity "{{ domain_name }}\Domain Users" -Publish }
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
  with_items: "{{ cert_templates }}"

- name: "Configure ATTRIBUTESUBJECTALTNAME2 on CA - ESC6"
  ansible.windows.win_shell: |
    certutil -config "{{ cauthority_server }}\{{ cauthority_common_name }}" -setreg policy\Editflags +EDITF_ATTRIBUTESUBJECTALTNAME2
  when: ca_vulns is defined and "'ESC6' in ca_vulns"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
    cauthority_server: "{{ hostname }}"
    cauthority_common_name: "{{ ca_common_name }}"

- name: Refresh
  ansible.windows.win_command: gpupdate /force