---
- name: Restart rsyncd
  ansible.builtin.service:
    name: "{{ rsyncd_service_name }}"
    state: restarted
    enabled: true

- name: Restart timer
  ansible.builtin.service:
    name: "rsyncd-clean.timer"
    state: restarted
    enabled: true
