- name: Prioritize the interface (local) as the default for routing '{{ domain_adapter }}'
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "{{ domain_adapter }}" -InterfaceMetric 10
  when: two_adapters


- name: Set configure dns to domain_dc_ip
  ansible.windows.win_dns_client:
    adapter_names: "{{ domain_adapter }}"
    ipv4_addresses:
      - "{{ domain_dc_ip }}"
    log_path: C:\dns_log.txt
