---
# handlers file for docker
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted

- name: Start and enable containerd
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: restarted
