- name: Add Replication Subnet
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $SubnetName,
          [String]
          $SiteName
      )
      Import-Module ActiveDirectory
      try {
        $Subnet = Get-ADReplicationSubnet -Identity $SubnetName
      }
      catch {
        $Subnet = $null
      }
      if ($null -ne $Subnet) {
        $Ansible.Changed = $false
      }
      else {
        $Ansible.Changed = $true
        New-ADReplicationSubnet -Name $SubnetName -Site $SiteName
      }
    parameters:
      SubnetName: "{{ item }}"
      SiteName: "{{ wd_cfg_subnet_site_name }}"
  with_items: "{{ wd_cfg_subnet_subnets }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ wd_cfg_subnet_domain_name }}\\Administrator"
    ansible_become_password: "{{ wd_cfg_subnet_domain_password }}"
