# https://rdr-it.com/en/active-directory-how-to-set-up-a-child-domain/#dns

# item == child domain
- name: Add dns delegation to child domain
  ansible.windows.win_shell: |
    Add-DnsServerZoneDelegation -Name "{{ domain }}" -ChildZoneName "{{ zone }}" -NameServer "{{ fqdn }}" -IPAddress "{{ ip }}" -PassThru -Verbose
  vars:
    domain: "{{ domain_name }}"
    fqdn: "{{ item[1] }}.{{ item[2] }}"
    ip: "{{ hostvars[item[0]].domain_ip }}"
    zone: "{{ item[2].split('.')[0] }}"
  loop: "{{ child_domains }}"


- name: Create conditional forwarder to child domain
  community.windows.win_dns_zone:
    name: "{{ item[2] }}"
    type: forwarder
    replication: "none"
    dns_servers:
      - "{{ ip }}"
  vars:
    ip: "{{ hostvars[item[0]].domain_ip }}"
  loop: "{{ child_domains }}"
