- name: Set acl on templates
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $for,
          [String]
          $to,
          [String]
          $right,
          [String]
          $inheritance
      )

      Import-Module -Name PSPKI

      #$c = get-command -Module PSPKI
      #Write-Output "template found : $c"

      $t = Get-CertificateTemplate -Name $to
      Write-Output "template found : $($t.DistinguishedName)"

      $acl = Get-CertificateTemplateAcl $t
      $str = $acl | FL | Out-String
      Write-Output "template ACL : $str"

      #Get-CertificateTemplate -Name $to |Get-CertificateTemplateAcl| Add-CertificateTemplateAcl -Identity $for `
      #  -AccessType Allow -AccessMask $right | Set-CertificateTemplateAcl
      $acl | Add-CertificateTemplateAcl -Identity $for -AccessType Allow -AccessMask $right | Set-CertificateTemplateAcl

    error_action: stop
    parameters:
      for: "{{ item.value.for }}"
      to: "{{ item.value.to }}"
      right: "{{ item.value.right }}"
      inheritance: "{{ item.value.inheritance }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
  with_dict: "{{ templates_acls }}"
  register: adcs_acl_template_result

# - debug:
#     var: adcs_acl_template_result
