- name: Validate AD Prepared
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $DefaultObjectVersion,
          [String]
          $ConfigObjectVersion,
          [String]
          $CorpName
      )
      Import-Module ActiveDirectory
      $Ansible.Changed = $false
      $Ansible.Failed = $false
      $c = $false
      $domain = Get-ADDomain
      try {
        $c = Get-ADObject -Identity "CN=Microsoft Exchange System Objects,$($domain.DistinguishedName)" -Property ObjectVersion | select ObjectVersion
      }
      Catch {
        $c=$false
      }
      if ($c -eq $false -or $c.ObjectVersion -ne $DefaultObjectVersion) {
        $Ansible.Failed = $true
      }
      try {
        $c = Get-ADObject -Identity "CN=$CorpName,CN=Microsoft Exchange,CN=Services,CN=Configuration,$($domain.DistinguishedName)" -Property ObjectVersion | select ObjectVersion
      }
      Catch {
        $c=$false
      }
      if ($c -eq $false -or $c.ObjectVersion -ne $ConfigObjectVersion) {
        $Ansible.Failed = $true
      }
    parameters:
      DefaultObjectVersion: "{{ wd_xchg_es_default_objectVersion }}"
      ConfigObjectVersion: "{{ wd_xchg_es_config_objectVersion }}"
      CorpName: "{{ wd_xchg_es_corp_name }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
  register: validate_ad_prepared
  ignore_errors: true