---
- name: assert proper distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Kali', 'Ubuntu', 'Archlinux']
    quiet: true

- include_tasks: "{{ ansible_distribution }}.yml" 

- name: Install timesyncd config
  ansible.builtin.template:
    src: templates/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
    owner: root
    group: root
  notify: Enable systemd-timesyncd

- name: Get timezone
  ansible.builtin.command: timedatectl status
  changed_when: false
  check_mode: false
  register: __timedatectl

- name: Set timezone
  ansible.builtin.command: /usr/bin/timedatectl set-timezone {{ tz_timezone }}
  when: 'tz_timezone |string not in __timedatectl.stdout'

- name: Set ntp on
  ansible.builtin.command: /usr/bin/timedatectl set-ntp on
  when: '"NTP service: active" not in __timedatectl.stdout'

- name: aAsert drop-in exist
  ansible.builtin.file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
