---
- name: Create logins mapping to specific users (non GMSA)
  ansible.windows.win_shell: |
    SqlCmd {{ connection_type }} "EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname = N'{{server}}', @locallogin = N'{{user_mapping.local_login}}', @useself = N'False', @rmtuser = N'{{user_mapping.remote_login}}', @rmtpassword = N'{{user_mapping.remote_password}}'"
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ sql_svc_account }}"
  vars:
    ansible_become_pass: "{{ sql_svc_password }}"
  loop: "{{ users_mapping }}"
  loop_control:
    loop_var: user_mapping
  when: not isgmsa

- name: Create logins mapping to specific users (GMSA)
  ansible.windows.win_shell: |
    c:\setup\PSExec64.exe -accepteula -i -u {{ sql_svc_account }} -p ~ SqlCmd {{ connection_type }} "EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname = N'{{server}}', @locallogin = N'{{user_mapping.local_login}}', @useself = N'False', @rmtuser = N'{{user_mapping.remote_login}}', @rmtpassword = N'{{user_mapping.remote_password}}'"
  loop: "{{ users_mapping }}"
  loop_control:
    loop_var: user_mapping
  when: isgmsa
