- name: Set connection method
  ansible.builtin.set_fact:
    connection_type: "{{ connection_type_2022 if sql_version == 'MSSQL_2022' else connection_type_2019 }}"

- name: Create SQL Linked server and enable RPC (non GMSA)
  ansible.windows.win_shell: |
    SqlCmd {{ connection_type }} "EXEC master.dbo.sp_addlinkedserver @server = N'{{ server }}', @srvproduct=N'', @provider=N'SQLOLEDB', @datasrc=N'{{ data_src }}'"
    SqlCmd {{ connection_type }} "EXEC master.dbo.sp_serveroption @server=N'{{ server }}', @optname=N'rpc', @optvalue=N'true'"
    SqlCmd {{ connection_type }} "EXEC master.dbo.sp_serveroption @server=N'{{ server }}', @optname=N'rpc out', @optvalue=N'true'"
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ sql_svc_account }}"
  vars:
    ansible_become_pass: "{{ sql_svc_password }}"
  when: not isgmsa

- name: Create SQL Linked server and enable RPC (GMSA)
  ansible.windows.win_shell: |
    c:\setup\PSExec64.exe -accepteula -i -u {{ sql_svc_account }} -p ~ SqlCmd {{ connection_type }} "EXEC master.dbo.sp_addlinkedserver @server = N'{{ server }}', @srvproduct=N'', @provider=N'SQLOLEDB', @datasrc=N'{{ data_src }}'"
    c:\setup\PSExec64.exe -accepteula -i -u {{ sql_svc_account }} -p ~ SqlCmd {{ connection_type }} "EXEC master.dbo.sp_serveroption @server=N'{{ server }}', @optname=N'rpc', @optvalue=N'true'"
    c:\setup\PSExec64.exe -accepteula -i -u {{ sql_svc_account }} -p ~ SqlCmd {{ connection_type }} "EXEC master.dbo.sp_serveroption @server=N'{{ server }}', @optname=N'rpc out', @optvalue=N'true'"
  when: isgmsa

- name: Create logins
  ansible.builtin.include_tasks: login.yml

- name: Default login impersonation (non GMSA)
  ansible.windows.win_shell: |
    SqlCmd {{ connection_type }} "EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname = N'{{ server }}', @locallogin = NULL , @useself = N'True'"
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ sql_svc_account }}"
  vars:
    ansible_become_pass: "{{ sql_svc_password }}"
  when: not isgmsa

- name: Default login impersonation (GMSA)
  ansible.windows.win_shell: |
    c:\setup\PSExec64.exe -accepteula -i -u {{ sql_svc_account }} -p ~ SqlCmd {{ connection_type }} "EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname = N'{{ server }}', @locallogin = NULL , @useself = N'True'"
  when: isgmsa
