- name: Add MSSQL admin (GMSA)
  ansible.windows.win_shell: |
    c:\setup\PSExec64.exe -accepteula -i -u {{ sql_svc_account }} -p ~ SqlCmd.exe {{ connection_type }} -Q "SP_ADDSRVROLEMEMBER '{{ item }}','SYSADMIN'"
  loop: "{{ sql_sysadmins }}"
  when: isgmsa
