- name: Add MSSQL admin (non GMSA)
  ansible.windows.win_shell: |
    SqlCmd {{ connection_type }} -Q "SP_ADDSRVROLEMEMBER '{{ item }}','SYSADMIN'"
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ sql_svc_account }}"
  vars:
    ansible_become_pass: "{{ sql_svc_password }}"
  loop: "{{ sql_sysadmins }}"
