

- name: install MECM (this one take an eternity ~ 1 hour  )
  win_shell: ConsoleSetup.exe /q "TargetDir=%ProgramFiles%\ConfigMgr Console" DefaultSiteServerName="{{hostvars[domain_dc_ansible_inventory_key].sccm_server}}.{{domain_name}}"
  args:
    chdir: C:\setup\cd.retail.LN\SMSSETUP\BIN\I386\
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_name}}\\Administrator"
    ansible_become_password: "{{domain_password}}"