- name: Create directory to store the downloaded prerequisite files
  ansible.windows.win_file:
    path: C:\setup
    state: directory


- name: Download Visual C++ 2017 Redistributable
  ansible.windows.win_get_url:
    url: https://aka.ms/vs/15/release/vc_redist.x64.exe
    dest: C:\setup\vc_redist.x64.exe
  register: download_vc_redist

- name: Install Visual C++ 2017 Redistributable
  ansible.windows.win_package:
    path: C:\setup\vc_redist.x64.exe
    arguments: /quiet /norestart
  when: download_vc_redist.changed

- name: Download MS SQL ODBC Driver 18
  ansible.windows.win_get_url: 
    url: https://go.microsoft.com/fwlink/?linkid=2280794
    dest: C:\setup\msodbcsql.msi 
  register: download_odbc

- name: Install MS SQL ODBC Driver 18 
  ansible.windows.win_package: 
    path: C:\setup\msodbcsql.msi 
    #product_id: '{566C6178-4AE9-40FF-A84F-4A021FF39816}'
    state: present 
    arguments: 
      - /passive  IACCEPTMSODBCSQLLICENSETERMS=YES /lv+ C:\setup\msodbcsql-install.log
  register: odbc_install
  when: download_odbc.changed

#- name: Install ODBC Mssql 18 driver
#  ansible.windows.win_package:
#    arguments: "IACCEPTMSODBCSQLLICENSETERMS=YES ALLUSERS=1"
#    #path: https://go.microsoft.com/fwlink/?linkid=2266640&clcid=0x409&culture=en-us&country=us
#    path: https://go.microsoft.com/fwlink/?linkid=2280794
#    state: present
#    creates_path: "%ProgramFiles%\\Microsoft SQL Server\\Client SDK\\ODBC"
#  register: odbc_install
#  until: odbc_install is success
#  retries: 3  # Try 3 times just in case it failed to download the URL
#  delay: 1

# https://download.microsoft.com/download/e/a/c/eac5a469-aa30-4fd5-a37b-508f6a2a0590/msodbcsql.msi
- name: Reboot after installing ODBC if required
  ansible.windows.win_reboot:
  when: odbc_install.reboot_required

- name: MECM installation media exists
  ansible.windows.win_stat:
    path: C:\setup\MCM_Configmgr_2303.exe
  register: mecm_installer_file

- name: Download MECM installation media
  ansible.windows.win_get_url:
    url: https://go.microsoft.com/fwlink/p/?LinkID=2195628&clcid=0x409&culture=en-us&country=us
    dest: C:\setup\MCM_Configmgr_2303.exe
  when: not mecm_installer_file.stat.exists

- name: Remove directory cd.retail.LN if exist
  ansible.windows.win_file:
    path: C:\setup\cd.retail.LN
    state: absent
  ignore_errors: true

# We should verify if the cd.retail.LN directory exists first.
# If yes, remove it.
- name: Extract MECM installation media
  ansible.windows.win_shell: .\MCM_Configmgr_2303.exe -s
  args:
    chdir: C:\setup\

- include_tasks: Install_console.yml 
  when: install_type == "console" 

- include_tasks: Install_server.yml 
  when: install_type == "server"
