# Step 14 – Download SCCM 1902 Baseline Media
# --------------------------------------------------------------
- name: Install ODBC Mssql 18 driver
  ansible.windows.win_package:
    arguments: "IACCEPTMSODBCSQLLICENSETERMS=YES ALLUSERS=1"
    path: https://go.microsoft.com/fwlink/?linkid=2266640&clcid=0x409&culture=en-us&country=us
    state: present
    creates_path: "%ProgramFiles%\\Microsoft SQL Server\\Client SDK\\ODBC"
  register: odbc_install
  until: odbc_install is success
  retries: 3  # Try 3 times just in case it failed to download the URL
  delay: 1

# https://download.microsoft.com/download/e/a/c/eac5a469-aa30-4fd5-a37b-508f6a2a0590/msodbcsql.msi
- name: Reboot after installing ODBC if required
  ansible.windows.win_reboot:
  when: odbc_install.reboot_required

- name: Create directory to store the downloaded prerequisite files
  ansible.windows.win_file:
    path: C:\setup
    state: directory

- name: MECM installation media exists
  ansible.windows.win_stat:
    path: C:\setup\MCM_Configmgr_2303.exe
  register: mecm_installer_file

- name: Download MECM installation media
  ansible.windows.win_get_url:
    url: https://go.microsoft.com/fwlink/p/?LinkID=2195628&clcid=0x409&culture=en-us&country=us
    dest: C:\setup\MCM_Configmgr_2303.exe
  when: not mecm_installer_file.stat.exists

- name: Remove directory cd.retail.LN if exist
  ansible.windows.win_file:
    path: C:\setup\cd.retail.LN
    state: absent
  ignore_errors: true

# We should verify if the cd.retail.LN directory exists first.
# If yes, remove it.
- name: Extract MECM installation media
  ansible.windows.win_shell: .\MCM_Configmgr_2303.exe -s
  args:
    chdir: C:\setup\

- include_tasks: install_console.yml 
  when: install_type == "console" 
- include_tasks: install_server.yml 
  when: install_type == "server"
