- name: "Prepare to trust flush and renew dns"
  ansible.windows.win_shell: |
    ipconfig /flushdns
    ipconfig /renew

# source : https://social.technet.microsoft.com/wiki/contents/articles/11911.active-directory-powershell-how-to-create-forest-trust.aspx
- name: Add trusts between domain
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $RemoteForest,

          [String]
          $RemoteAdmin,

          [String]
          $RemoteAdminPassword
      )
      $localforest=[System.DirectoryServices.ActiveDirectory.Forest]::getCurrentForest()
      try {
        $localForest.GetTrustRelationship($RemoteForest)
        $Ansible.Changed = $false
      } catch {
        $Ansible.Changed = $true
        $remoteContext = New-Object -TypeName "System.DirectoryServices.ActiveDirectory.DirectoryContext" `
          -ArgumentList @( "Forest", $RemoteForest, $RemoteAdmin, $RemoteAdminPassword)
        $distantForest = [System.DirectoryServices.ActiveDirectory.Forest]::getForest($remoteContext)
        $localForest.CreateTrustRelationship($distantForest,"Bidirectional")
      }
    error_action: stop
    parameters:
      RemoteForest: "{{ domain_trust_remote_domain_name }}"
      RemoteAdmin: "Administrator@{{ domain_trust_remote_domain_name }}"
      RemoteAdminPassword: "{{ domain_trust_remote_domain_password }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ domain_name }}\\Administrator"
    ansible_become_password: "{{ domain_password }}"
  register:
    trust_result
  notify:
    Reboot and wait for the AD system to restart
#        $localForest.CreateTrustRelationship($distantForest,"Bidirectional")
#        $localForest.CreateTrustRelationship($distantForest,"Inbound")
- name: Flush reboot handlers
  ansible.builtin.meta:
    flush_handlers
