---
#  BLUEtooth
  #   cp /etc/pulse ~/.config/pulse
  #   load-module module-switch-on-connect >> ~/.config/pulse/default.pa
  #
- name: Install packages
  community.general.pacman:
    name: "{{ bluetoot_headset_pkgs }}"
    state: present
    update_cache: true

