- name: Install AUR packages
  include_role:
    name: aur-install
  vars:
    aur_pkg_name: "{{ item }}"
  loop:
    - xpub
    - batify
- name: Install pacman packages
  community.general.pacman:
    name: dunst
    update_cache: true
