
#- name: Compute template name
#  ansible.builtin.set_fact:
#   wallix_bastion_authentication_domain_json: "{{ wallix_bastion_authentication_domain_data.type | lower }}.json.j2"


- name: Render Wallix Bastion JSON payload
  ansible.builtin.set_fact:
   wallix_bastion_authentication_domain_json: "{{ lookup('template', (wallix_bastion_authentication_domain_data.type | lower) + '.json.j2') }}"

- name: Debug Wallix Bastion JSON payload
  ansible.builtin.debug:
    var: wallix_bastion_authentication_domain_json

- name: "Create Wallix Bastion device account {{ wallix_bastion_authentication_domain_name }}"
  ansible.builtin.uri:
    url: "{{ wallix_bastion_authentication_domain_url }}/authdomains"
    method: POST
    body_format: json
    validate_certs: false
    status_code:
      - 204
    headers:
      Cookie: "wab_session_id={{ wallix_bastion_authentication_domain_cookie.cookies['wab_session_id'] }}"
    body: "{{ wallix_bastion_authentication_domain_json }}"



