---
- name: Restart timer_full
  ansible.builtin.service:
    name: "sslbackup-full.timer"
    state: restarted
    enabled: true
- name: Restart timer_diff
  ansible.builtin.service:
    name: "sslbackup-diff.timer"
    state: restarted
    enabled: true
