- name: Set connection method
  ansible.builtin.set_fact:
    connection_type: "{{ connection_type_2022 if sql_version == 'MSSQL_2022' else connection_type_2019 }}"

- name: Domain Account (GMSA)
  ansible.builtin.include_tasks: sqlcmd_gmsa.yml
  when: isgmsa

- name: Domain Account (non GMSA)
  ansible.builtin.include_tasks: sqlcmd.yml
  when: not isgmsa
