- name: Create local account
  ansible.windows.win_shell: |
   SqlCmd {{ connection_type }} -Q "CREATE LOGIN [{{ item }}] WITH PASSWORD = N'{{ item.value }}'"
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ SQLSVCACCOUNT }}"
  with_dict: "{{ mssql_localaccounts }}"
  when: not ISGMSA
