- name: Create local account
  ansible.windows.win_shell: |
   c:\setup\PSExec64.exe -accepteula -i -u {{SQLSVCACCOUNT}} -p ~ SqlCmd.exe {{connection_type}} -Q "CREATE LOGIN [{{ item }}] WITH PASSWORD = N'{{ item.value }}'"
  with_dict: "{{ mssql_localaccounts }}"
  when: ISGMSA
