---
- name: Ensure OU is present
  microsoft.ad.ou:
    name: "{{ item.value.name }}"
    path: "{{ item.value.path }}"
    state: present
    domain_username: "{{ windows_domain_gpo_cfg_domain_name }}\\Administrator"
    domain_password: "{{ windows_domain_gpo_cfg_domain_password }}"
  with_dict: "{{ windows_domain_gpo_cfg_ous }}"

- name: Install GPO feature
  ansible.windows.win_feature:
    name: GPMC
    state: present
    include_sub_features: true
    include_management_tools: true
  register: win_feature

- name: Create GPO
  win_gpo:
    name: '{{ windows_domain_gpo_cfg_name }}'
    description: '{{ windows_domain_gpo_cfg_desc }}'
    state: present
  register: pri_gpo

# - name: Add LAPS extension to GPO
#   win_ad_object:
#     name: '{{ pri_laps_gpo.path }}'
#     attributes:
#       # [Registry:Admin Tool][AdmPwd:Admin Tool]
#       gPCMachineExtensionNames: "[{35378EAC-683F-11D2-A89A-00C04FBBCFA2}{D02B1F72-3407-48AE-BA88-E8213C6761F1}]\
#         [{D76B9641-3288-4F75-942D-087DE603E3EA}{D02B1F72-3407-48AE-BA88-E8213C6761F1}]"


- name: CConfigure GPO with registry
  win_gpo_reg:
    gpo: '{{ windows_domain_gpo_cfg_name }}'
    name: '{{ reg.key }}'
    path: "{{ reg.value.path }}"
    state: "{{ reg.value.state }}"
    type: "{{ reg.value.type }}"
    value: "{{ reg.value.value }}"
  loop: "{{ windows_domain_gpo_cfg_registry | dict2items }}"
  loop_control:
    loop_var: reg


- name: Create Comment File for GPO
  ansible.windows.win_copy:
    src: ../files/comment.cmtx
    dest: C:\Windows\SYSVOL\domain\Policies\{{ '{' }}{{ pri_gpo.id }}{{ '}' }}\Machine\comment.cmtx

- name: Ensure GPO is Linked on OU
  win_gpo_link:
    name: '{{ windows_domain_gpo_cfg_name }}'
    target: "OU={{ item.value.name }},{{ item.value.path }}"
    state: '{{ item.value.state }}'
    enforced: '{{ item.value.enforced }}'
    enabled: '{{ item.value.enabled }}'
  with_dict: "{{ windows_domain_gpo_cfg_ous }}"

- name: Ensure GPO is Linked on Domain
  win_gpo_link:
    name: '{{ windows_domain_gpo_cfg_name }}'
    target: "{{ windows_domain_gpo_cfg_domain_ldap_name }}"
    state: '{{ windows_domain_gpo_cfg_domain_state }}'
    enforced: '{{ windows_domain_gpo_cfg_domain_enforced }}'
    enabled: '{{ windows_domain_gpo_cfg_domain_enabled }}'
  when: windows_domain_gpo_cfg_domain
