- name: Create directory for repositories
  ansible.windows.win_file:
    path: "c:\\users\\{{ windows_domain_git_clone_user }}\\Desktop\\repositories"
    state: directory
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ windows_domain_git_clone_net_bios }}\\{{ windows_domain_git_clone_user }}"
    ansible_become_password: "{{ windows_domain_git_clone_password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

- name: Install repos
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]
        $Repo,
        [String]
        $Folder,
        [String]
        $Base
      )
      if (-Not (Test-Path -Path $Base\$Folder)) {
        git clone -q $Repo $Base\$Folder
      }
    error_action: stop
    parameters:
      Repo: "{{ item[1] }}"
      Folder: "{{ item[0] }}"
      Base: "c:\\users\\{{ windows_domain_git_clone_user }}\\Desktop\\repositories"
  loop: "{{ windows_domain_git_clone_repositories }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ windows_domain_git_clone_net_bios }}\\{{ windows_domain_git_clone_user }}"
    ansible_become_password: "{{ windows_domain_git_clone_password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
