---
- name: Install pacman packages
  community.general.pacman:
    name: "{{ item }}"
    update_cache: true
  register: __pacman
  changed_when: (__pacman.packages | default([])) | length >0
  loop: "{{ wifi_ap_packages }}"

- name: Install hostapd-mana
  ansible.builtin.include_role:
    name: aur-install
  vars:
    aur_pkg_name: hostapd-mana-git
