---
- name: Install pacman packages
  community.general.pacman:
    name: "{{ wifi_ap_packages }}"
    update_cache: true

- name: Install hostapd-mana
  ansible.builtin.include_role:
    name: aur-install
  vars:
    aur_pkg_name: hostapd-mana-git
