---
- name: Assert proper distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Archlinux']
    quiet: true

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Include common variables
  ansible.builtin.include_vars: "common.yml"

# - name: Assettions cheks
#   ansible.builtin.include_tasks: asserts.yml

- name: OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: Reboot
  ansible.builtin.reboot:
