# https://petri.com/configure-dns-on-domain-controller-two-ip-addresses/
- name: "Set DS DNS to listen on domain interface {{ windows_domain_dns_listening_domain_dc_ip }}"
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $IP
      )
      Import-Module ActiveDirectory
      Set-Location AD:

      try {
        $s= Get-DnsServerSetting -ALL
        $s.ListeningIpAddress = @($IP)
        Set-DNSServerSetting $s
        $Ansible.Failed = $false
      } catch {
        $Ansible.Failed = $true
        $message = $_
        Write-Warning "Something happened! $message"
      }
    error_action: stop
    parameters:
      IP: "{{ windows_domain_dns_listening_domain_dc_ip }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ windows_domain_dns_listening_domain_name }}\\Administrator"
    ansible_become_password: "{{ windows_domain_dns_listening_domain_password }}"
  register: set_dns_server_ip
  when: windows_domain_dns_listening_two_adapters

# - debug:
#     var: set_dns_server_ip
#   when: two_adapters

- name: Retrieve DNS Server config
  ansible.windows.win_shell: |
    $obj = Get-DnsServerSetting
    Write-Output  $obj
  register: get_dns_server_listeningip
  when: windows_domain_dns_listening_two_adapters

# - name: Show DNS Server config
#   debug:
#     var: get_dns_server_listeningip
#   when: two_adapters

- name: Reboot
  ansible.windows.win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 100
  when: windows_domain_dns_listening_two_adapters

- name: Retrieve DNS Server config
  ansible.windows.win_shell: |
    $obj = Get-DnsServerSetting
    Write-Output  $obj
  register: get_dns_server_listeningip
  when: windows_domain_dns_listening_two_adapters

- name: Show DNS Server config
  ansible.builtin.debug:
    var: get_dns_server_listeningip
  when: windows_domain_dns_listening_two_adapters
