- name: Ensure OU is present
  microsoft.ad.ou:
    name: "{{ item.value.name }}"
    path: "{{ item.value.path }}"
    protect_from_deletion: false
    state: present
    domain_username: "{{ wd_cfg_ou_domain_name }}\\Administrator"
    domain_password: "{{ wd_cfg_ou_domain_password }}"
  with_dict: "{{ wd_cfg_ou_ous | default({}) }}"
  register: oucreate
