---
- name: Assert proper distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Archlinux', 'Kali']
    quiet: true

- name: Assert locales_gen is well defined
  ansible.builtin.assert:
    that:
      - locales_gen is defined
      - locales_gen is sequence
    quiet: true

- name: Assert every locales_gen is well defined
  ansible.builtin.assert:
    that:
      - item is string
    quiet: true
  with_items: "{{ locales_gen }}"

- name: Assert local_lang is well defined
  ansible.builtin.assert:
    that:
      - locale_lang is defined
      - locale_lang is string
    quiet: true

- name: Assert vconsole_content is well defined
  ansible.builtin.assert: 
    that:
      - vconsole_content is defined
      - vconsole_content is string
    quiet: true
