---
- name: Validate prerequisits
  ansible.builtin.include_tasks: asserts.yml

- name: Specify locale
  ansible.builtin.template:
    src: templates/locale.gen.j2
    dest: /etc/locale.gen
    mode: '0644'
    owner: root
    group: root
  notify: Generate locale

- name: Set locale
  ansible.builtin.template:
    src: templates/locale.conf.j2
    dest: /etc/locale.conf
    mode: '0644'
    owner: root
    group: root

- name: Set vconsole
  ansible.builtin.copy:
    content: "{{ vconsole_content }}"
    dest: /etc/vconsole.conf
    mode: '0644'
    owner: root
    group: root
